# ERREUR ATTENDUE (sémantique) : deux servers sur le même host:port,
# le deuxième bind() échouerait -> refus de démarrer (exigence du sujet).

server {
    listen 8080;
    host 127.0.0.1;

    location / {
        root www;
        methods GET;
    }
}

server {
    listen 8080;
    host 127.0.0.1;

    location / {
        root www;
        methods GET;
    }
}
