# ERREUR ATTENDUE (sémantique) : deux locations "/" dans le même server,
# le router ne saurait pas laquelle choisir.

server {
    listen 8080;
    host 127.0.0.1;

    location / {
        root www;
        methods GET;
    }

    location / {
        root www/uploads;
        methods POST;
    }
}
