# ERREUR ATTENDUE (sémantique) : cette location n'a ni root, ni redirect,
# ni cgi -> elle ne peut rien faire d'une requête.

server {
    listen 8080;
    host 127.0.0.1;

    location / {
        methods GET;
        autoindex on;
    }
}
