# ERREUR ATTENDUE (sémantique) : pas de directive 'listen',
# le serveur ne saurait pas sur quel port écouter.

server {
    host 127.0.0.1;

    location / {
        root www;
        methods GET;
    }
}
