# La config la plus petite possible acceptée par le validator :
# un server = un listen + un host + une location avec une action.

server {
    listen 8081;
    host 127.0.0.1;

    location / {
        root www;
        methods GET;
    }
}
